import Foundation

typealias CreateAccountScreenViewModelType = CreateAccountScreenViewModelInput & CreateAccountScreenViewModelOutput

protocol CreateAccountScreenViewModelInput {}

protocol CreateAccountScreenViewModelOutput {}
